version: '3.3'

services:
  postgres:
    # container_name: postgres_db
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=duman
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=duman
      - MYSQL_PASSWORD=admin123
      # - MYSQL_ROOT_HOST= '%'
      # - MYSQL_PORT=3306
    volumes:
      - ./volumenes/mysql:/var/lib/mysql
    expose:
      - 3306
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysql #<Previous SERVICE mysql:
    ports:
      - 8080:80
